apiVersion: v1
kind: Pod
metadata:
  name: shell
  labels:
    name: shell
spec:
  containers:
  - name: shell
    image: centos:7
    command: ["sh", "-c", "sleep 3600"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "50m"
