kind: Pod
apiVersion: v1
metadata:
  name: shell
  labels:
    name: shell
spec:
  nodeSelector:
    kubernetes.io/hostname: node-0
  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Equal"
    effect: "NoSchedule"
  containers:
  - name: shell
    image: ubuntu
    command:
      - sh
      - -c
      - "sleep 3600"
