kind: Pod
apiVersion: v1
metadata:
  name: wordpress-backup
  labels:
    app: wordpress
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - wordpress
        topologyKey: kubernetes.io/hostname
  containers:
  - name: wordpress-backup
    image: busybox
    command:
    - sh
    - -c
    - "sleep 3600"
