apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  labels:
    component: kube-scheduler
    tier: control-plane
    app: my-scheduler
  name: my-kube-scheduler
  namespace: kube-system
spec:
  nodeSelector:
    kubernetes.io/hostname: node-0
  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Equal"
    effect: "NoSchedule"
  containers:
  - command:
    - kube-scheduler
    - --config=/etc/kubernetes/scheduler/kube-scheduler-config.yaml
    image: k8s.gcr.io/kube-scheduler:v1.13.2
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-scheduler
    resources:
      requests:
        cpu: 100m
    volumeMounts:
    - mountPath: /etc/kubernetes/scheduler.conf
      name: kubeconfig
      readOnly: true
    - mountPath: /etc/kubernetes/scheduler
      name: kube-scheduler-configmap
  hostNetwork: false
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/kubernetes/scheduler.conf
      type: FileOrCreate
    name: kubeconfig
  - name: kube-scheduler-configmap
    configMap:
      name: my-scheduler-config-map
status: {}
