apiVersion: v1
kind: ConfigMap
metadata:
  name: my-scheduler-config-map
  namespace: kube-system
  labels:
    app: my-scheduler
data:
  kube-scheduler-config.yaml: |-
    algorithmSource:
      provider: DefaultProvider
    apiVersion: kubescheduler.config.k8s.io/v1alpha1
    bindTimeoutSeconds: 600
    clientConnection:
      acceptContentTypes: ""
      burst: 100
      contentType: application/vnd.kubernetes.protobuf
      kubeconfig: "/etc/kubernetes/scheduler.conf"
      qps: 50
    disablePreemption: false
    enableContentionProfiling: false
    enableProfiling: false
    failureDomains: kubernetes.io/hostname,failure-domain.beta.kubernetes.io/zone,failure-domain.beta.kubernetes.io/region
    hardPodAffinitySymmetricWeight: 1
    healthzBindAddress: 0.0.0.0:10251
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    metricsBindAddress: 0.0.0.0:10251
    percentageOfNodesToScore: 50
    schedulerName: my-scheduler
    policyConfigMap: my-scheduler-policy-cm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-scheduler-policy-cm
  namespace: kube-system
  labels:
    app: my-scheduler
data: 
  scheduler-policy.yaml: |
    kind: Policy
    apiVersion: v1
    predicates:
    - name: PodFitsPorts
    - name: PodFitsResources
    - name: NoDiskConflict
    - name: MatchNodeSelector
    - name: HostName
    priorities:
    - name: LeastRequestedPriority
      weight: 1
    - name: BalancedResourceAllocation
      weight: 1
    - name: ServiceSpreadingPriority
      weight: 1
    - name: EqualPriority
      weight: 1