kind: Pod
apiVersion: v1
metadata:
  name: shell
  namespace: limitrange
  labels:
    name: shell
spec:
  containers:
  - name: shell
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 128Mi

